---
- name: play to create different set of users based on server group
  hosts: [sun,galaxy,earth]
  become: true
  vars:
   u1: smaria01
   u2: soradb01
   u3: smongo01
   u4: scomm01
  become_user: root
 
  tasks:
  
  - name: task to create users for group inventory sun
    user:
      name: "{{u1}}"
      state: present
    when: inventory_hostname in groups['sun']
  
  - name: task to create users for group inventory galaxy
    user:
      name: "{{u2}}"
      state: present
    when: inventory_hostname in groups['galaxy']
  
  - name: task to create users for group inventory earth
    user:
      name: "{{u3}}"
      state: present
    when: inventory_hostname in groups['earth']
  
  
  - name: task to create users for group inventory earth or sun
    user:
      name: "{{u4}}"
      state: present
    when: inventory_hostname in groups['earth'] or inventory_hostname in groups['sun']
...
